services:
  go-fiber-core:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.api.${APP_ENV}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
      - ./cmd:/app/cmd
      - ./internal:/app/internal
      - ./.air.toml:/app/.air.toml
    command: >
      sh -c "if [ ${APP_ENV} = 'local' ]; then air; else /app/bin/app; fi"
    networks:
      - nginx-proxy
