services:
  traefik:
    image: traefik:v3.1
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "${TRAEFIK_HTTP_PORT}:80"
      - "${TRAEFIK_HTTPS_PORT}:443"
      - "${TRAEFIK_DASHBOARD_PORT}:${TRAEFIK_DASHBOARD_PORT}" # Dashboard http://localhost:8080/dashboard#/
    volumes:
      - ./certs:/etc/traefik/certs:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nginx-proxy
