services:
  sqsv4-${API_PORT}:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
      args:
        FOLDER: ${FOLDER}
    volumes:
      - .:/app:cached
    ports:
      - "${API_PORT:-8080}:${API_PORT:-8080}"
    environment:
      environment:
      - FOLDER=${FOLDER}
      - APP_ENV=local
      - GO111MODULE=on
    networks:
      - nginx-proxy
    env_file: .env
    command: ["-c", ".air-${FOLDER}.toml"]
