services:
  sqsv4-dev-api:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.dev
      args:
        FOLDER: api
    volumes:
      - .:/app:cached
    ports:
      - "${API_PORT:-8080}:${API_PORT:-8080}"
    environment:
      - APP_ENV=local
      - GO111MODULE=on
      - API_PORT=${API_PORT:-8080}
    networks:
      - nginx-proxy
    env_file: .env
    command: ["-c", ".air-api.toml"]
