services:
  sqsv4-dev-sqs-consumer:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
      args:
        FOLDER: api
    volumes:
      - .:/app:cached
    ports:
      - ":8080"
    environment:
      - APP_ENV=local
      - GO111MODULE=on
    networks:
      - nginx-proxy
    env_file: .env
    command: ["-c", ".air-sqs-consumer.toml"]
