http:
  routers:
    go-fiber-core-router:
      rule: "Host(`local.bankfilegen.test`)"
      entryPoints:
        - websecure
      service: "go-fiber-core-service"
      tls: {}

  services:
    go-fiber-core-service:
      loadBalancer:
        servers:
          - url: "http://go-fiber-core-api-go-fiber-core-1:9009"
          - url: "http://go-fiber-core-api-go-fiber-core-2:9009"

tls:
  certificates:
    - certFile: /etc/traefik/certs/cert.pem
      keyFile: /etc/traefik/certs/key.pem
